### ISSUE TITLE
Question: What model does BERT-score uses?

### ISSUE THREAD

**Issue by luckysusanto** [wangcunxiang/QA-Eval#2]
The paper mentioned the use of BERT-score. Does it use the base pre-trained BERT? Or is it further fine-tuned?

**Comment by wangcunxiang** [comment]
It is a base pretrained BERT. You can check it in https://arxiv.org/pdf/1904.09675 and https://github.com/Tiiiger/bert_score

**Comment by luckysusanto** [comment]
Thanks! Solved.
